### ISSUE TITLE
[Feedback] Manifest creation and media

### ISSUE THREAD

**Issue by jdchart** [SCENE-CE/mirador-multi-user#259]
The current system for adding Media to a Canvas is problematic. Notably absence of feedback and the user having to use urls. Proposed solution:

- [ ] At first, the media tab in not open.
- [ ] When the user has clicked Add Canvas, add a **+** button between the url text field and Remove Media button. When the user clicks on the button:
  - It turns into a **tick** (indicating that they must click again to confirm what they are changing).
  - The media tab opens (indicating they must choose a media)
  - As long as the user has not clicked on the tick, whenever they click on a media, the url automatically gets pasted into the text field (allowing them to click on different media, changing the url each time.
  - When they click on the **tick**, it turns back to a **+**. Now when they click on Medias, it no longer pastes anything into the text field (but the URL is still copied to the clipboard).
- [ ] Empty media url default text shoudl read: "Select a media to ass it to your page"

**Comment by daxid** [comment]
@jdchart Unfortunatly your proposed solution is not doable in a sound manner. The reason is:

1. adding manifests to a workspace in Mirador (not yet developed) will use the same UI as adding a media in a manifest
2. we cannot implement your proposition in the context of Mirador for technical reasons
3. we chose to implement a workflow that is consistent in all parts of the UI
